<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LolHolmes.Domain\LolHolmes.Domain.csproj" />
    <ProjectReference Include="..\LolHolmes.Infrastructure\LolHolmes.Infrastructure.csproj" />
  </ItemGroup>

</Project>
